# Generated by Django 5.1.7 on 2025-03-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
